# Generated by Django 5.1.4 on 2025-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(max_length=10)),
            ],
        ),
    ]
