# Generated by Django 5.0 on 2025-03-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_webflyer_webflyerflyer_webflyerposting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumResult',
        ),
        migrations.DeleteModel(
            name='TestPost',
        ),
        migrations.DeleteModel(
            name='WebFlyer',
        ),
        migrations.DeleteModel(
            name='WebFlyerFlyer',
        ),
        migrations.DeleteModel(
            name='WebFlyerPosting',
        ),
    ]
