# Generated by Django 5.0 on 2025-03-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_sumresult_delete_testpost_delete_webflyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=4)),
                ('school_name', models.CharField(max_length=20)),
                ('apply_name', models.CharField(max_length=20)),
                ('apply_year', models.IntegerField()),
                ('apply_month', models.IntegerField()),
                ('excel_file_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebFlyerFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=4)),
                ('school_name', models.CharField(max_length=20)),
                ('total_out', models.IntegerField()),
                ('total_inquiry', models.IntegerField()),
                ('total_consult', models.IntegerField()),
                ('flyer_item1', models.CharField(max_length=100)),
                ('attached_item1', models.CharField(max_length=100)),
                ('place1', models.CharField(max_length=100)),
                ('place_detail1', models.CharField(max_length=100)),
                ('flyer_count1', models.IntegerField()),
                ('memo1', models.CharField(max_length=100)),
                ('flyer_item2', models.CharField(max_length=100)),
                ('attached_item2', models.CharField(max_length=100)),
                ('place2', models.CharField(max_length=100)),
                ('place_detail2', models.CharField(max_length=100)),
                ('flyer_count2', models.IntegerField()),
                ('memo2', models.CharField(max_length=100)),
                ('flyer_item3', models.CharField(max_length=100)),
                ('attached_item3', models.CharField(max_length=100)),
                ('place3', models.CharField(max_length=100)),
                ('place_detail3', models.CharField(max_length=100)),
                ('flyer_count3', models.IntegerField()),
                ('memo3', models.CharField(max_length=100)),
            ],
        ),
    ]
