# Generated by Django 5.0 on 2025-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sumresult_testpost_webflyer_webflyerflyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('visible_name', models.CharField(max_length=100)),
            ],
        ),
    ]
