# Generated by Django 5.0 on 2025-04-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebFlyer',
        ),
        migrations.DeleteModel(
            name='WebFlyerFlyer',
        ),
    ]
